[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "day1"
path = "src/day1/main.rs"
